//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSCFieldApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSCFieldApp.Resources.Strings.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string GenericNoteTitle {
            get {
                return ResourceManager.GetString("GenericNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Books.
        /// </summary>
        internal static string ShellFieldBooksTitle {
            get {
                return ResourceManager.GetString("ShellFieldBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Notes.
        /// </summary>
        internal static string ShellFieldNotesTitle {
            get {
                return ResourceManager.GetString("ShellFieldNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string ShellMapTitle {
            get {
                return ResourceManager.GetString("ShellMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Backup.
        /// </summary>
        internal static string ShellQuickBackupTitle {
            get {
                return ResourceManager.GetString("ShellQuickBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ShellSettingsTitle {
            get {
                return ResourceManager.GetString("ShellSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current station notes.
        /// </summary>
        internal static string StationPageCurrentNotePlaceholder {
            get {
                return ResourceManager.GetString("StationPageCurrentNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Photo #.
        /// </summary>
        internal static string StationPageGeneralAirPhoto {
            get {
                return ResourceManager.GetString("StationPageGeneralAirPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phys. Environment.
        /// </summary>
        internal static string StationPageGeneralPhysEnv {
            get {
                return ResourceManager.GetString("StationPageGeneralPhysEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        internal static string StationPageGeneralRelatedTo {
            get {
                return ResourceManager.GetString("StationPageGeneralRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. another station alias.
        /// </summary>
        internal static string StationPageGeneralRelatedToPlaceholder {
            get {
                return ResourceManager.GetString("StationPageGeneralRelatedToPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string StationPageGeneralTitle {
            get {
                return ResourceManager.GetString("StationPageGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse #.
        /// </summary>
        internal static string StationPageGeneralTravNo {
            get {
                return ResourceManager.GetString("StationPageGeneralTravNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string StationPageOutcropQuality {
            get {
                return ResourceManager.GetString("StationPageOutcropQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string StationPageOutcropSize {
            get {
                return ResourceManager.GetString("StationPageOutcropSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 10m.
        /// </summary>
        internal static string StationPageOutcropSizePlaceholder {
            get {
                return ResourceManager.GetString("StationPageOutcropSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcrop.
        /// </summary>
        internal static string StationPageOutcropTitle {
            get {
                return ResourceManager.GetString("StationPageOutcropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since last station.
        /// </summary>
        internal static string StationPageSLSPlaceholder {
            get {
                return ResourceManager.GetString("StationPageSLSPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string StationPageSource {
            get {
                return ResourceManager.GetString("StationPageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string StationPageTitle {
            get {
                return ResourceManager.GetString("StationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string StationPageType {
            get {
                return ResourceManager.GetString("StationPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string StationPageTypeTitle {
            get {
                return ResourceManager.GetString("StationPageTypeTitle", resourceCulture);
            }
        }
    }
}
