//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSCFieldApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSCFieldApp.Resources.Strings.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clast Form.
        /// </summary>
        internal static string EarthmatPageClast {
            get {
                return ResourceManager.GetString("EarthmatPageClast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string EarthmatPageColourTitle {
            get {
                return ResourceManager.GetString("EarthmatPageColourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string EarthmatPageContactTitle {
            get {
                return ResourceManager.GetString("EarthmatPageContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type detail ie. basalt.
        /// </summary>
        internal static string EarthmatPageDetailSearchPlaceholder {
            get {
                return ResourceManager.GetString("EarthmatPageDetailSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string EarthmatPageGeneralTitle {
            get {
                return ResourceManager.GetString("EarthmatPageGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation.
        /// </summary>
        internal static string EarthmatPageInterpretationTitle {
            get {
                return ResourceManager.GetString("EarthmatPageInterpretationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedding Thickness.
        /// </summary>
        internal static string EarthmatPageLithBedThick {
            get {
                return ResourceManager.GetString("EarthmatPageLithBedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformation Fabric.
        /// </summary>
        internal static string EarthmatPageLithDefFab {
            get {
                return ResourceManager.GetString("EarthmatPageLithDefFab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain/Crystal Size.
        /// </summary>
        internal static string EarthmatPageLithGrainSize {
            get {
                return ResourceManager.GetString("EarthmatPageLithGrainSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Unit.
        /// </summary>
        internal static string EarthmatPageLithMapUnit {
            get {
                return ResourceManager.GetString("EarthmatPageLithMapUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs as.
        /// </summary>
        internal static string EarthmatPageLithOccurAs {
            get {
                return ResourceManager.GetString("EarthmatPageLithOccurAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string EarthmatPageLithoDetail {
            get {
                return ResourceManager.GetString("EarthmatPageLithoDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithologic Modifiers.
        /// </summary>
        internal static string EarthmatPageLithoModTitle {
            get {
                return ResourceManager.GetString("EarthmatPageLithoModTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithology - Setting and composition.
        /// </summary>
        internal static string EarthmatPageLithoTitle {
            get {
                return ResourceManager.GetString("EarthmatPageLithoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string EarthmatPageLithoType {
            get {
                return ResourceManager.GetString("EarthmatPageLithoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string EarthmatPageLithPercent {
            get {
                return ResourceManager.GetString("EarthmatPageLithPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifier.
        /// </summary>
        internal static string EarthmatPageLithQualifier {
            get {
                return ResourceManager.GetString("EarthmatPageLithQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture/Structure.
        /// </summary>
        internal static string EarthmatPageLithTextStruc {
            get {
                return ResourceManager.GetString("EarthmatPageLithTextStruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetism.
        /// </summary>
        internal static string EarthmatPageMagTitle {
            get {
                return ResourceManager.GetString("EarthmatPageMagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic Facies.
        /// </summary>
        internal static string EarthmatPageMetaFaciesTitle {
            get {
                return ResourceManager.GetString("EarthmatPageMetaFaciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineralogy.
        /// </summary>
        internal static string EarthmatPageMineralogyTitle {
            get {
                return ResourceManager.GetString("EarthmatPageMineralogyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxidation.
        /// </summary>
        internal static string EarthmatPageOxidation {
            get {
                return ResourceManager.GetString("EarthmatPageOxidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}% ({1}).
        /// </summary>
        internal static string EarthmatPageResidualLabel {
            get {
                return ResourceManager.GetString("EarthmatPageResidualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type group ie. metamorphic.
        /// </summary>
        internal static string EarthmatPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("EarthmatPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string EarthmatPageSorting {
            get {
                return ResourceManager.GetString("EarthmatPageSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Material.
        /// </summary>
        internal static string EarthmatPageTitle {
            get {
                return ResourceManager.GetString("EarthmatPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2O Content.
        /// </summary>
        internal static string EarthmatPageWater {
            get {
                return ResourceManager.GetString("EarthmatPageWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new fossil.
        /// </summary>
        internal static string EarthmatTooltipAddFossil {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new mineralization/alteration.
        /// </summary>
        internal static string EarthmatTooltipAddMA {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new mineral.
        /// </summary>
        internal static string EarthmatTooltipAddMineral {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddMineral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new paleoflow.
        /// </summary>
        internal static string EarthmatTooltipAddPaleoflow {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddPaleoflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new sample.
        /// </summary>
        internal static string EarthmatTooltipAddSample {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new structure.
        /// </summary>
        internal static string EarthmatTooltipAddStruc {
            get {
                return ResourceManager.GetString("EarthmatTooltipAddStruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string FieldBookPageActivty {
            get {
                return ResourceManager.GetString("FieldBookPageActivty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Summer 2023.
        /// </summary>
        internal static string FieldBookPageActivtyPlaceholder {
            get {
                return ResourceManager.GetString("FieldBookPageActivtyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FieldBookPageChiefFName {
            get {
                return ResourceManager.GetString("FieldBookPageChiefFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string FieldBookPageChiefLName {
            get {
                return ResourceManager.GetString("FieldBookPageChiefLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string FieldBookPageChiefMName {
            get {
                return ResourceManager.GetString("FieldBookPageChiefMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FieldBookPageDescriptionTitle {
            get {
                return ResourceManager.GetString("FieldBookPageDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geologist.
        /// </summary>
        internal static string FieldBookPageGeologistTitle {
            get {
                return ResourceManager.GetString("FieldBookPageGeologistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Code.
        /// </summary>
        internal static string FieldBookPageOfficerCode {
            get {
                return ResourceManager.GetString("FieldBookPageOfficerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        internal static string FieldBookPageOfficerCodePlaceholder {
            get {
                return ResourceManager.GetString("FieldBookPageOfficerCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string FieldBookPageOtherTitle {
            get {
                return ResourceManager.GetString("FieldBookPageOtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string FieldBookPageProject {
            get {
                return ResourceManager.GetString("FieldBookPageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEM Melville.
        /// </summary>
        internal static string FieldBookPageProjectPlaceholder {
            get {
                return ResourceManager.GetString("FieldBookPageProjectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Leader.
        /// </summary>
        internal static string FieldBookPageProjectTitle {
            get {
                return ResourceManager.GetString("FieldBookPageProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Start Number.
        /// </summary>
        internal static string FieldBookPageSSN {
            get {
                return ResourceManager.GetString("FieldBookPageSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Book.
        /// </summary>
        internal static string FieldBookPageTitle {
            get {
                return ResourceManager.GetString("FieldBookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type.
        /// </summary>
        internal static string FieldBookPageWorkType {
            get {
                return ResourceManager.GetString("FieldBookPageWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Materials.
        /// </summary>
        internal static string FielNotesEMHeader {
            get {
                return ResourceManager.GetString("FielNotesEMHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string FielNotesSampleHeader {
            get {
                return ResourceManager.GetString("FielNotesSampleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string FielNotesStationHeader {
            get {
                return ResourceManager.GetString("FielNotesStationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string GenericButtonCancel {
            get {
                return ResourceManager.GetString("GenericButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string GenericButtonDelete {
            get {
                return ResourceManager.GetString("GenericButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GenericButtonOk {
            get {
                return ResourceManager.GetString("GenericButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string GenericNoteTitle {
            get {
                return ResourceManager.GetString("GenericNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Books.
        /// </summary>
        internal static string ShellFieldBooksTitle {
            get {
                return ResourceManager.GetString("ShellFieldBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Notes.
        /// </summary>
        internal static string ShellFieldNotesTitle {
            get {
                return ResourceManager.GetString("ShellFieldNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not saved successfully with error:.
        /// </summary>
        internal static string ShellFileSaveFail {
            get {
                return ResourceManager.GetString("ShellFileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was saved successfully to location:.
        /// </summary>
        internal static string ShellFileSaveSuccess {
            get {
                return ResourceManager.GetString("ShellFileSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string ShellMapTitle {
            get {
                return ResourceManager.GetString("ShellMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Backup.
        /// </summary>
        internal static string ShellQuickBackupTitle {
            get {
                return ResourceManager.GetString("ShellQuickBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ShellSettingsTitle {
            get {
                return ResourceManager.GetString("ShellSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current station notes.
        /// </summary>
        internal static string StationPageCurrentNotePlaceholder {
            get {
                return ResourceManager.GetString("StationPageCurrentNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Photo #.
        /// </summary>
        internal static string StationPageGeneralAirPhoto {
            get {
                return ResourceManager.GetString("StationPageGeneralAirPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phys. Environment.
        /// </summary>
        internal static string StationPageGeneralPhysEnv {
            get {
                return ResourceManager.GetString("StationPageGeneralPhysEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        internal static string StationPageGeneralRelatedTo {
            get {
                return ResourceManager.GetString("StationPageGeneralRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. another station alias.
        /// </summary>
        internal static string StationPageGeneralRelatedToPlaceholder {
            get {
                return ResourceManager.GetString("StationPageGeneralRelatedToPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string StationPageGeneralTitle {
            get {
                return ResourceManager.GetString("StationPageGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse #.
        /// </summary>
        internal static string StationPageGeneralTravNo {
            get {
                return ResourceManager.GetString("StationPageGeneralTravNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string StationPageNotesCurrent {
            get {
                return ResourceManager.GetString("StationPageNotesCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since Last Station.
        /// </summary>
        internal static string StationPageNotesSLS {
            get {
                return ResourceManager.GetString("StationPageNotesSLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string StationPageOutcropQuality {
            get {
                return ResourceManager.GetString("StationPageOutcropQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string StationPageOutcropSize {
            get {
                return ResourceManager.GetString("StationPageOutcropSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 10m.
        /// </summary>
        internal static string StationPageOutcropSizePlaceholder {
            get {
                return ResourceManager.GetString("StationPageOutcropSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcrop.
        /// </summary>
        internal static string StationPageOutcropTitle {
            get {
                return ResourceManager.GetString("StationPageOutcropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since last station.
        /// </summary>
        internal static string StationPageSLSPlaceholder {
            get {
                return ResourceManager.GetString("StationPageSLSPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string StationPageSource {
            get {
                return ResourceManager.GetString("StationPageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string StationPageTitle {
            get {
                return ResourceManager.GetString("StationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string StationPageType {
            get {
                return ResourceManager.GetString("StationPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string StationPageTypeTitle {
            get {
                return ResourceManager.GetString("StationPageTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new earth material.
        /// </summary>
        internal static string StationTooltipAddEM {
            get {
                return ResourceManager.GetString("StationTooltipAddEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new environment.
        /// </summary>
        internal static string StationTooltipAddEnv {
            get {
                return ResourceManager.GetString("StationTooltipAddEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add a new mineralization/alteration.
        /// </summary>
        internal static string StationTooltipAddMA {
            get {
                return ResourceManager.GetString("StationTooltipAddMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add one or many photos.
        /// </summary>
        internal static string StationTooltipAddPhoto {
            get {
                return ResourceManager.GetString("StationTooltipAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was saved successfully to location: {0}.
        /// </summary>
        internal static string ToastSaveBackup {
            get {
                return ResourceManager.GetString("ToastSaveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not saved successfully with error: {0}.
        /// </summary>
        internal static string ToastSaveBackupFailed {
            get {
                return ResourceManager.GetString("ToastSaveBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a new field book.
        /// </summary>
        internal static string WatermarkNoFieldBook {
            get {
                return ResourceManager.GetString("WatermarkNoFieldBook", resourceCulture);
            }
        }
    }
}
